### ISSUE TITLE
Need Chinese translations for website i18n.

### ISSUE THREAD

**Issue by thoward** [jsconfcn/jingjs#3]
Current only one small phrase is i18n translated. See comments in js/i18n.js for instructions on how to add translations.

**Comment by fengmk2** [comment]
@goddyZhao It' time for your show.

**Comment by goddyZhao** [comment]
I'll handle that, J!

## Thanks

Goddy
http://goddyzhao.me

**Comment by goddyZhao** [comment]
Sent the PR
